MODULE FIELD_API_BASIC_TYPE_MOD

USE FIELD_BASIC_MODULE, ONLY: FIELD_BASIC

IMPLICIT NONE

TYPE FIELD_BASIC_PTR
  CLASS (FIELD_BASIC), POINTER :: PTR
  INTEGER, ALLOCATABLE         :: IVSET(:)
  CHARACTER(LEN=10)            :: NAME
END TYPE

END MODULE FIELD_API_BASIC_TYPE_MOD

