! (C) Copyright 2001- ECMWF.
! (C) Copyright 2001- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE FIELD_API_ECTRANS_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_ACCESS_MODULE, ONLY: GET_HOST_DATA_RDWR, GET_DEVICE_DATA_RDWR, GET_HOST_DATA_RDONLY,GET_DEVICE_DATA_RDONLY
USE FIELD_BASIC_MODULE, ONLY: FIELD_BASIC
USE FIELD_MODULE, ONLY:FIELD_1RB, FIELD_2RB, FIELD_3RB, FIELD_4RB, FIELD_2RB_VIEW, FIELD_3RB_VIEW
USE FIELD_API_BASIC_TYPE_MOD, ONLY: FIELD_BASIC_PTR
IMPLICIT NONE

TYPE SPEC_VIEW
  ! Spectral field view
  TYPE (FIELD_2RB_VIEW) :: VIEW
  INTEGER               :: IVSET
  CHARACTER(LEN=12)     :: NAME
END TYPE

TYPE GRID_VIEW
! Grid point field view
  TYPE (FIELD_3RB_VIEW) :: VIEW  
  CHARACTER(LEN=12)     :: NAME
END TYPE

INTERFACE B
  MODULE PROCEDURE :: B1RB, B2RB, B3RB, B4RB
END INTERFACE

CONTAINS

FUNCTION B1RB(YLF,NAME, IVSET)
! Creation of a FIELD_BASIC_PTR encapsulating a FIELD_1RB field
CLASS (FIELD_1RB), POINTER :: YLF
CHARACTER(LEN=*) :: NAME
INTEGER, OPTIONAL :: IVSET(:)
TYPE (FIELD_BASIC_PTR) :: B1RB

B1RB%PTR => YLF
IF (PRESENT(IVSET)) THEN
  ALLOCATE(B1RB%IVSET(SIZE(IVSET)))
  B1RB%IVSET = IVSET
ENDIF
B1RB%NAME = NAME

END FUNCTION B1RB

FUNCTION B2RB(YLF,NAME,IVSET)
! Creation of a FIELD_BASIC_PTR encapsulating a FIELD_2RB field
CLASS (FIELD_2RB), POINTER :: YLF
CHARACTER(LEN=*) :: NAME

INTEGER, OPTIONAL :: IVSET(:)
TYPE (FIELD_BASIC_PTR) :: B2RB

B2RB%PTR => YLF
IF (PRESENT(IVSET)) THEN
  ALLOCATE(B2RB%IVSET(SIZE(IVSET)))
  B2RB%IVSET = IVSET
ENDIF
B2RB%NAME = NAME

END FUNCTION B2RB

FUNCTION B3RB(YLF,NAME,IVSET)
! Creation of a FIELD_BASIC_PTR encapsulating a FIELD_3RB field
CLASS (FIELD_3RB), POINTER :: YLF
CHARACTER(LEN=*) ::NAME
INTEGER, OPTIONAL :: IVSET(:)
TYPE (FIELD_BASIC_PTR) :: B3RB

B3RB%PTR => YLF
IF (PRESENT(IVSET)) THEN
  ALLOCATE(B3RB%IVSET(SIZE(IVSET)))
  B3RB%IVSET = IVSET
ENDIF
B3RB%NAME = NAME

END FUNCTION B3RB

FUNCTION B4RB(YLF,NAME,IVSET)
! Creation of a FIELD_BASIC_PTR encapsulating a FIELD_4RB field
CLASS (FIELD_4RB), POINTER :: YLF
CHARACTER(LEN=*) ::NAME
INTEGER, OPTIONAL :: IVSET(:)
TYPE (FIELD_BASIC_PTR) :: B4RB

B4RB%PTR => YLF

IF (PRESENT(IVSET)) THEN
  ALLOCATE(B4RB%IVSET(SIZE(IVSET)))
  B4RB%IVSET = IVSET
ENDIF
B4RB%NAME = NAME

END FUNCTION B4RB

FUNCTION LG2RB (YLF,NAME,LDACC,LDRDONLY)
! Creation of a list of GRID_VIEW encapsulating the layer of an input FIELD_2RB field
! Given YLF dimensioned(NPROMA, NBLKS) as input,
! the output list size will contain one element, its view beeing dimensioned(NPROMA, NBLKS)
CLASS (FIELD_2RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
LOGICAL :: LDACC
LOGICAL :: LDRDONLY

TYPE (GRID_VIEW), ALLOCATABLE :: LG2RB (:)

REAL(KIND=JPRB), POINTER :: ZZ2 (:,:)
CHARACTER(LEN=6) CLOUT
IF (LDACC) THEN
  IF (LDRDONLY) THEN
    ZZ2 => GET_DEVICE_DATA_RDONLY(YLF)
  ELSE
    ZZ2 => GET_DEVICE_DATA_RDWR(YLF)
  ENDIF
ELSE
  IF (LDRDONLY) THEN
    ZZ2 => GET_HOST_DATA_RDONLY(YLF)
  ELSE
    ZZ2 => GET_HOST_DATA_RDWR(YLF)
  ENDIF
ENDIF

ALLOCATE (LG2RB (1))

LG2RB (1)%VIEW%P => ZZ2

LG2RB(1)%NAME = TRIM(NAME)//TRIM(CLOUT)
END FUNCTION

FUNCTION LG3RB (YLF,NAME, LDACC,LDRDONLY)
! Creation of a list of GRID_VIEW encapsulating the layers of an input FIELD_3RB field
! Given YLF dimensioned(NPROMA, NLEVS, NBLKS) as input,
! the output list size will contain  (NLEVS) elements, their view beeing dimensioned(NPROMA, NBLKS)
CLASS (FIELD_3RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
LOGICAL :: LDACC
LOGICAL :: LDRDONLY

TYPE (GRID_VIEW), ALLOCATABLE :: LG3RB (:)

REAL(KIND=JPRB), POINTER :: ZZ3 (:,:,:)
INTEGER(KIND=JPIM) :: JLEV, JCOUNT
CHARACTER(LEN=6) CLOUT

IF (LDACC) THEN
  IF (LDRDONLY) THEN
    ZZ3 => GET_DEVICE_DATA_RDONLY(YLF)
  ELSE
    ZZ3 => GET_DEVICE_DATA_RDWR(YLF)
  ENDIF
ELSE
  IF (LDRDONLY) THEN
    ZZ3 => GET_HOST_DATA_RDONLY(YLF)
  ELSE
    ZZ3 => GET_HOST_DATA_RDWR(YLF)
  ENDIF
ENDIF

ALLOCATE (LG3RB (SIZE (ZZ3, 2)))

JCOUNT = 1
DO JLEV = LBOUND (ZZ3, 2), UBOUND (ZZ3, 2)
  LG3RB (JCOUNT)%VIEW%P => ZZ3 (:, JLEV, :)
  LG3RB(JCOUNT)%NAME = TRIM(NAME)//TRIM(CLOUT)
  JCOUNT = JCOUNT + 1
ENDDO

END FUNCTION

FUNCTION LG4RB (YLF,NAME,LDACC,LDRDONLY)
! Creation of a list of GRID_VIEW encapsulating the layers of an input FIELD_4RB field
! Given YLF dimensioned(NPROMA, NLEVS, NFIELDS, NBLKS) as input,
! the output list size will contain  (NLEVS*NFIELDS) elementa, their view beeing dimensioned(NPROMA, NBLKS)

CLASS (FIELD_4RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
LOGICAL :: LDACC
LOGICAL :: LDRDONLY

TYPE (GRID_VIEW), ALLOCATABLE :: LG4RB (:)

REAL(KIND=JPRB), POINTER :: ZZ4 (:,:,:,:)
INTEGER(KIND=JPIM) :: JLEV, JFLD, JCOUNT

CHARACTER(LEN=6) CLOUT

IF (LDACC) THEN
  IF (LDRDONLY) THEN
    ZZ4 => GET_DEVICE_DATA_RDONLY(YLF)
  ELSE
    ZZ4 => GET_DEVICE_DATA_RDWR(YLF)
  ENDIF
ELSE
  IF (LDRDONLY) THEN
    ZZ4 => GET_HOST_DATA_RDONLY(YLF)
  ELSE
    ZZ4 => GET_HOST_DATA_RDWR(YLF)
  ENDIF
ENDIF

ALLOCATE (LG4RB (SIZE (ZZ4, 2) * SIZE (ZZ4, 3)))

JCOUNT = 1

DO JFLD = LBOUND (ZZ4, 3), UBOUND (ZZ4, 3)
  DO JLEV = LBOUND (ZZ4, 2), UBOUND (ZZ4, 2)
    LG4RB (JCOUNT)%VIEW%P => ZZ4(:, JLEV, JFLD, :)
    LG4RB(JCOUNT)%NAME = TRIM(NAME)//TRIM(CLOUT)
    JCOUNT = JCOUNT + 1
  ENDDO
ENDDO

END FUNCTION

FUNCTION LG (YLFL,LDACC,LDRDONLY)
! Creation of a list of GRID_VIEW from a list YLFL of FIELD_BASIC_PTR
TYPE (FIELD_BASIC_PTR) :: YLFL (:)      ! input list of FIELD_BASIC_PTR
LOGICAL :: LDACC                        ! retrieve data on device
LOGICAL :: LDRDONLY
TYPE (GRID_VIEW), ALLOCATABLE :: LG (:) ! output list of GRID_VIEW

INTEGER(KIND=JPIM) :: IOFF, ILEN, JFLD, JPASS
INTEGER(KIND=JPIM) :: ILBOUNDS (5), IUBOUNDS (5)

! First pass: determination of the output size list
! Second pass: allocate and instanciate the GRID_VIEW types
DO JPASS = 1, 2

  IOFF = 0

  ! iterate over YLFL LIST
  DO JFLD = 1, SIZE (YLFL)

   ! Phase 1: compute number of GRID_VIEW that will be generated for each field of the list
   ! Phase 2: call the correct routine to create the GRID_VIEW for each field of the list
    SELECT TYPE (YLF => YLFL (JFLD)%PTR)
      CLASS IS (FIELD_1RB)
        ILEN = 1
      CLASS IS (FIELD_2RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
        ILEN = 1
        IF (JPASS == 2) LG (IOFF+1:IOFF+ILEN) = LG2RB (YLF,YLFL(JFLD)%NAME,LDACC,LDRDONLY)
      CLASS IS (FIELD_3RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
        ILEN = (IUBOUNDS (2) - ILBOUNDS (2) + 1)
        IF (JPASS == 2) LG (IOFF+1:IOFF+ILEN) = LG3RB (YLF,YLFL(JFLD)%NAME, LDACC,LDRDONLY)
      CLASS IS (FIELD_4RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
        ILEN = (IUBOUNDS (2) - ILBOUNDS (2) + 1) * (IUBOUNDS (3) - ILBOUNDS (3) + 1)
        IF (JPASS == 2) LG (IOFF+1:IOFF+ILEN) = LG4RB (YLF,YLFL(JFLD)%NAME, LDACC,LDRDONLY)
      CLASS DEFAULT
        CALL ABOR1("LG FAILURE: CLASS UNKNOWN")
    END SELECT

    IOFF = IOFF + ILEN

  ENDDO

  ! at the end of the first pass, allocation of the list of GRID_VIEW
  IF (JPASS == 1) THEN
    ALLOCATE (LG (IOFF))
  ENDIF

ENDDO

END FUNCTION LG

FUNCTION LS1RB (YLF, NAME, IVSET, LDACC,LDRDONLY)
! Creation of a list of SPEC_VIEW encapsulating the layer of an input FIELD_1RB field
! Given YLF dimensioned(NSPEC) as input,
! the output list size will contain one element, its view beeing dimensioned(NSPEC)
CLASS (FIELD_1RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
INTEGER :: IVSET(:)
LOGICAL :: LDACC
LOGICAL :: LDRDONLY

CHARACTER(LEN=6) CLOUT
TYPE (SPEC_VIEW), ALLOCATABLE :: LS1RB (:)

REAL(KIND=JPRB), POINTER :: ZZ1 (:)

IF (LDACC) THEN
  IF (LDRDONLY) THEN
    ZZ1 => GET_DEVICE_DATA_RDONLY(YLF)
  ELSE
    ZZ1 => GET_DEVICE_DATA_RDWR(YLF)
  ENDIF
ELSE
  IF (LDRDONLY) THEN
    ZZ1 => GET_HOST_DATA_RDONLY(YLF)
  ELSE
    ZZ1 => GET_HOST_DATA_RDWR(YLF)
  ENDIF
ENDIF

ALLOCATE (LS1RB (1))

LS1RB(1)%VIEW%P => ZZ1
LS1RB(1)%IVSET = IVSET(1)
LS1RB(1)%NAME=TRIM(NAME)//TRIM(CLOUT)

END FUNCTION

FUNCTION LS2RB (YLF,NAME, IVSET, LDACC,LDRDONLY)
! Creation of a list of SPEC_VIEW, each of them encapsulating a layer of an input FIELD_2RB field.
! Given YLF dimensioned(NLEVS, NSPEC) as input,
! the output list size will contain (NLEVS) elements dimensioned(NSPEC)
CLASS (FIELD_2RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
INTEGER :: IVSET(:)
LOGICAL :: LDACC
LOGICAL :: LDRDONLY

CHARACTER(LEN=6) CLOUT
TYPE (SPEC_VIEW), ALLOCATABLE :: LS2RB (:)

REAL(KIND=JPRB), POINTER :: ZZ2 (:,:)
INTEGER(KIND=JPIM) :: JLEV, JCOUNT
IF (LDACC) THEN
  IF (LDRDONLY) THEN
    ZZ2 => GET_DEVICE_DATA_RDONLY(YLF)
  ELSE
    ZZ2 => GET_DEVICE_DATA_RDWR(YLF)
  ENDIF
ELSE
  IF (LDRDONLY) THEN
    ZZ2 => GET_HOST_DATA_RDONLY(YLF)
  ELSE
    ZZ2 => GET_HOST_DATA_RDWR(YLF)
  ENDIF
ENDIF

ALLOCATE (LS2RB (SIZE (ZZ2, 1)))

JCOUNT = 1

DO JLEV = LBOUND (ZZ2, 1), UBOUND (ZZ2, 1)
  LS2RB (JCOUNT)%VIEW%P => ZZ2 (JLEV, :)
  LS2RB (JCOUNT)%IVSET = IVSET(JLEV)
  LS2RB(JCOUNT)%NAME=TRIM(NAME)//TRIM(CLOUT)
  JCOUNT = JCOUNT + 1
ENDDO

END FUNCTION

FUNCTION LS3RB (YLF,NAME, IVSET, LDACC,LDRDONLY)
! Creation of a list of SPEC_VIEW, each of them encapsulating a layer of an input FIELD_3RB field.
! Given YLF dimensioned(NLEVS, NSPEC, NFIELDS) as input,
! the output list size will contain (NLEVS*NFIELDS) SPEC_VIEW, each of them dimensioned(NSPEC)
  CLASS (FIELD_3RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) :: NAME
LOGICAL :: LDACC
INTEGER :: IVSET(:)
LOGICAL :: LDRDONLY

CHARACTER(LEN=6) CLOUT
TYPE (SPEC_VIEW), ALLOCATABLE :: LS3RB (:)

REAL(KIND=JPRB), POINTER :: ZZ3 (:,:,:)
INTEGER(KIND=JPIM) :: JLEV, JFLD, JCOUNT

IF (LDACC) THEN
  IF (LDRDONLY) THEN
    ZZ3 => GET_DEVICE_DATA_RDONLY(YLF)
  ELSE
    ZZ3 => GET_DEVICE_DATA_RDWR(YLF)
  ENDIF
ELSE
  IF (LDRDONLY) THEN
    ZZ3 => GET_HOST_DATA_RDONLY(YLF)
  ELSE
    ZZ3 => GET_HOST_DATA_RDWR(YLF)
  ENDIF
ENDIF


ALLOCATE (LS3RB (SIZE (ZZ3, 1) * SIZE (ZZ3, 3)))

JCOUNT = 1

DO JFLD = LBOUND (ZZ3, 3), UBOUND (ZZ3, 3)
  DO JLEV = LBOUND (ZZ3, 1), UBOUND (ZZ3, 1)
    LS3RB(JCOUNT)%VIEW%P => ZZ3 (JLEV, :, JFLD)
    LS3RB(JCOUNT)%NAME=TRIM(NAME)//TRIM(CLOUT)
    LS3RB(JCOUNT)%IVSET = IVSET(JLEV)
    JCOUNT = JCOUNT + 1
  ENDDO
ENDDO

END FUNCTION

FUNCTION LS (YLFL,LDACC,LDRDONLY)
! Creation of a list of SPEC_VIEW from a list YLFL of FIELD_BASIC_PTR
  TYPE (FIELD_BASIC_PTR) :: YLFL (:)       ! input list of FIELD_BASIC_PTR
  TYPE (SPEC_VIEW), ALLOCATABLE :: LS (:)  ! output list of SPEC_VIEW
  LOGICAL  LDACC                 ! retrieve data on device
  LOGICAL  LDRDONLY

INTEGER(KIND=JPIM) :: IOFF, ILEN, JFLD, JPASS
INTEGER(KIND=JPIM) :: ILBOUNDS (5), IUBOUNDS (5)

! First pass: determination of the output size list
! Second pass: allocate and instanciate the SPEC_VIEW types
DO JPASS = 1, 2

  IOFF = 0
  ILEN = -1

  ! iterate over YLFL LIST
  DO JFLD = 1, SIZE (YLFL)

   ! Phase 1: compute number of SPEC_VIEW that will be generated for each field of the list
   ! Phase 2: call the correct routine to create the SPEC_VIEW for each field of the list
    SELECT TYPE (YLF => YLFL (JFLD)%PTR)
      CLASS IS (FIELD_1RB)
        ILEN = 1
        IF (JPASS == 2) LS (IOFF+1:IOFF+ILEN) = LS1RB (YLF,YLFL(JFLD)%NAME,YLFL(JFLD)%IVSET, LDACC,LDRDONLY)
      CLASS IS (FIELD_2RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
        ILEN = (IUBOUNDS (1) - ILBOUNDS (1) + 1)
        IF (JPASS == 2) LS (IOFF+1:IOFF+ILEN) = LS2RB (YLF,YLFL(JFLD)%NAME,YLFL(JFLD)%IVSET, LDACC,LDRDONLY)
      CLASS IS (FIELD_3RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
         ILEN =  (IUBOUNDS (1) - ILBOUNDS (1) + 1)* (IUBOUNDS (3) - ILBOUNDS (3) + 1)
        IF (JPASS == 2) LS (IOFF+1:IOFF+ILEN) = LS3RB (YLF ,YLFL(JFLD)%NAME,YLFL(JFLD)%IVSET, LDACC,LDRDONLY)
      CLASS IS (FIELD_4RB)
          CALL ABOR1("LS not implemeted for FIELD_4RB")
      CLASS DEFAULT
         ! Skip the spectral field as it is not present on this processor
         ILEN = 1
    END SELECT

    IOFF = IOFF + ILEN

  ENDDO

  ! at the end of the first pass, allocation of the list of SPEC_VIEW
  IF (JPASS == 1) THEN
    ALLOCATE (LS(IOFF))
  ENDIF

ENDDO

END FUNCTION LS


SUBROUTINE COPY_DEVICE_1RB (PTR_RHS, PTR_LHS)

  REAL(KIND=JPRB) :: PTR_RHS (:), PTR_LHS (:)
  
  !$acc kernels present (PTR_RHS, PTR_LHS)
  PTR_RHS = PTR_LHS
  !$acc end kernels
  
END SUBROUTINE

SUBROUTINE COPY_DEVICE_2RB (PTR_RHS, PTR_LHS)

  REAL(KIND=JPRB) :: PTR_RHS (:,:), PTR_LHS (:,:)
  
  !$acc kernels present (PTR_RHS, PTR_LHS)
  PTR_RHS = PTR_LHS
  !$acc end kernels
  
END SUBROUTINE
  
    


END MODULE FIELD_API_ECTRANS_MOD

