! (C) Copyright 2001- ECMWF.
! (C) Copyright 2001- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE FIELD_API_ECTRANS_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_ACCESS_MODULE, ONLY: GET_HOST_DATA_RDWR, GET_DEVICE_DATA_RDWR
USE FIELD_BASIC_MODULE, ONLY: FIELD_BASIC
USE FIELD_MODULE, ONLY:FIELD_1RB, FIELD_2RB, FIELD_3RB, FIELD_4RB, FIELD_2RB_VIEW, FIELD_3RB_VIEW
USE FIELD_API_BASIC_TYPE_MOD, ONLY: FIELD_BASIC_PTR
IMPLICIT NONE

TYPE SPEC_VIEW
  ! Spectral field view
  TYPE (FIELD_2RB_VIEW) :: VIEW
  CHARACTER(LEN=12)     :: NAME
END TYPE

TYPE GRID_VIEW
! Grid point field view
  TYPE (FIELD_3RB_VIEW) :: VIEW
  INTEGER               :: IVSET
  CHARACTER(LEN=12)     :: NAME
END TYPE

INTERFACE B
  MODULE PROCEDURE :: B1RB, B2RB, B3RB, B4RB
END INTERFACE

CONTAINS

FUNCTION B1RB(YLF,NAME, IVSET)
! Creation of a FIELD_BASIC_PTR encapsulating a FIELD_1RB field
CLASS (FIELD_1RB), POINTER :: YLF
CHARACTER(LEN=*) :: NAME
INTEGER, OPTIONAL :: IVSET(:)
TYPE (FIELD_BASIC_PTR) :: B1RB

B1RB%PTR => YLF
IF (PRESENT(IVSET)) THEN
  ALLOCATE(B1RB%IVSET(SIZE(IVSET)))
  B1RB%IVSET = IVSET
ENDIF
B1RB%NAME = NAME

END FUNCTION B1RB

FUNCTION B2RB(YLF,NAME,IVSET)
! Creation of a FIELD_BASIC_PTR encapsulating a FIELD_2RB field
CLASS (FIELD_2RB), POINTER :: YLF
CHARACTER(LEN=*) :: NAME

INTEGER, OPTIONAL :: IVSET(:)
TYPE (FIELD_BASIC_PTR) :: B2RB

B2RB%PTR => YLF
IF (PRESENT(IVSET)) THEN
  ALLOCATE(B2RB%IVSET(SIZE(IVSET)))
  B2RB%IVSET = IVSET
ENDIF
B2RB%NAME = NAME

END FUNCTION B2RB

FUNCTION B3RB(YLF,NAME,IVSET)
! Creation of a FIELD_BASIC_PTR encapsulating a FIELD_3RB field
CLASS (FIELD_3RB), POINTER :: YLF
CHARACTER(LEN=*) ::NAME
INTEGER, OPTIONAL :: IVSET(:)
TYPE (FIELD_BASIC_PTR) :: B3RB

B3RB%PTR => YLF
IF (PRESENT(IVSET)) THEN
  ALLOCATE(B3RB%IVSET(SIZE(IVSET)))
  B3RB%IVSET = IVSET
ENDIF
B3RB%NAME = NAME

END FUNCTION B3RB

FUNCTION B4RB(YLF,NAME,IVSET)
! Creation of a FIELD_BASIC_PTR encapsulating a FIELD_4RB field
CLASS (FIELD_4RB), POINTER :: YLF
CHARACTER(LEN=*) ::NAME
INTEGER, OPTIONAL :: IVSET(:)
TYPE (FIELD_BASIC_PTR) :: B4RB

B4RB%PTR => YLF

IF (PRESENT(IVSET)) THEN
  ALLOCATE(B4RB%IVSET(SIZE(IVSET)))
  B4RB%IVSET = IVSET
ENDIF
B4RB%NAME = NAME

END FUNCTION B4RB

FUNCTION LG2RB (YLF,NAME,IVSET, LDACC)
! Creation of a list of GRID_VIEW encapsulating an input FIELD_2RB field
! Given YLF dimensioned(NPROMA, NBLKS) as input,
! the output list size will contain one GRID_VIEW containing a VIEW dimensioned(NPROMA, NBLKS)
CLASS (FIELD_2RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
INTEGER :: IVSET(:)
LOGICAL, OPTIONAL :: LDACC

TYPE (GRID_VIEW), ALLOCATABLE :: LG2RB (:)

REAL(KIND=JPRB), POINTER :: ZZ2 (:,:)
INTEGER(KIND=JPIM) :: I2, I3, J
LOGICAL :: LLACC = .FALSE.
CHARACTER(LEN=6) CLOUT

IF (PRESENT(LDACC)) THEN
  LLACC = LDACC
END IF

IF (LLACC) THEN
  ZZ2 => GET_DEVICE_DATA_RDWR(YLF)
ELSE
  ZZ2 => GET_HOST_DATA_RDWR(YLF)
ENDIF

ALLOCATE (LG2RB (1))

LG2RB (1)%VIEW%P => ZZ2
LG2RB (1)%IVSET = IVSET(1)

LG2RB(1)%NAME = TRIM(NAME)//TRIM(CLOUT)
END FUNCTION

FUNCTION LG3RB (YLF,NAME, IVSET,LDACC)
! Creation of a GRID_VIEW encapsulating a FIELD_3RB field
CLASS (FIELD_3RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
INTEGER :: IVSET(:)
LOGICAL, OPTIONAL :: LDACC

TYPE (GRID_VIEW), ALLOCATABLE :: LG3RB (:)

REAL(KIND=JPRB), POINTER :: ZZ3 (:,:,:)
INTEGER(KIND=JPIM) :: I2, J
LOGICAL :: LLACC = .FALSE.

CHARACTER(LEN=6) CLOUT
IF (PRESENT(LDACC)) THEN
  LLACC = LDACC
END IF

IF (LLACC) THEN
  ZZ3 => GET_DEVICE_DATA_RDWR(YLF)
ELSE
  ZZ3 => GET_HOST_DATA_RDWR(YLF)
ENDIF

ALLOCATE (LG3RB (SIZE (ZZ3, 2)))

J = 1
DO I2 = LBOUND (ZZ3, 2), UBOUND (ZZ3, 2)
  LG3RB (J)%VIEW%P => ZZ3 (:, I2, :)
  LG3RB (J)%IVSET = IVSET(I2)
  LG3RB(J)%NAME = TRIM(NAME)//TRIM(CLOUT)
  J = J + 1
ENDDO

END FUNCTION

FUNCTION LG4RB (YLF,NAME,IVSET,LDACC)
! Creation of a GRID_VIEW encapsulating a FIELD_4RB field
CLASS (FIELD_4RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
INTEGER :: IVSET(:)
LOGICAL, OPTIONAL :: LDACC

TYPE (GRID_VIEW), ALLOCATABLE :: LG4RB (:)

REAL(KIND=JPRB), POINTER :: ZZ4 (:,:,:,:)
INTEGER(KIND=JPIM) :: I2, I3, J
LOGICAL :: LLACC = .FALSE.

CHARACTER(LEN=6) CLOUT
IF (PRESENT(LDACC)) THEN
  LLACC = LDACC
END IF

IF (LLACC) THEN
  ZZ4 => GET_DEVICE_DATA_RDWR(YLF)
ELSE
  ZZ4 => GET_HOST_DATA_RDWR(YLF)
ENDIF

ALLOCATE (LG4RB (SIZE (ZZ4, 2) * SIZE (ZZ4, 3)))

J = 1

DO I3 = LBOUND (ZZ4, 3), UBOUND (ZZ4, 3)
  DO I2 = LBOUND (ZZ4, 2), UBOUND (ZZ4, 2)
    LG4RB (J)%VIEW%P => ZZ4(:, I2, I3, :)
    LG4RB (J)%IVSET = IVSET(I2) 
    LG4RB(J)%NAME = TRIM(NAME)//TRIM(CLOUT)
    J = J + 1
  ENDDO
ENDDO

END FUNCTION

FUNCTION LG (YLFL, LDACC)
! Creation of a list of GRID_VIEW from a list FIELD_BASIC_PTR
TYPE (FIELD_BASIC_PTR) :: YLFL (:) ! input list of FIELD_BASIC_PTR
LOGICAL, OPTIONAL :: LDACC         ! data on device
TYPE (GRID_VIEW), ALLOCATABLE :: LG (:) !output list of GRID_VIEW

INTEGER(KIND=JPIM) :: IOFF, ILEN, JFLD, JPASS
INTEGER(KIND=JPIM) :: ILBOUNDS (5), IUBOUNDS (5)

DO JPASS = 1, 2

  IOFF = 0

  DO JFLD = 1, SIZE (YLFL)
    SELECT TYPE (YLF => YLFL (JFLD)%PTR)
      CLASS IS (FIELD_1RB)
        ILEN = 1
      CLASS IS (FIELD_2RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
        ILEN = 1
        IF (JPASS == 2) LG (IOFF+1:IOFF+ILEN) = LG2RB (YLF,YLFL(JFLD)%NAME,YLFL(JFLD)%IVSET,LDACC)
      CLASS IS (FIELD_3RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
        ILEN = (IUBOUNDS (2) - ILBOUNDS (2) + 1)
        IF (JPASS == 2) LG (IOFF+1:IOFF+ILEN) = LG3RB (YLF,YLFL(JFLD)%NAME,YLFL(JFLD)%IVSET, LDACC)
      CLASS IS (FIELD_4RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
        ILEN = (IUBOUNDS (2) - ILBOUNDS (2) + 1) * (IUBOUNDS (3) - ILBOUNDS (3) + 1)
        IF (JPASS == 2) LG (IOFF+1:IOFF+ILEN) = LG4RB (YLF,YLFL(JFLD)%NAME,YLFL(JFLD)%IVSET,LDACC)
      CLASS DEFAULT
        WRITE(20,*) YLFL(JFLD)%NAME
        CALL ABOR1("LG FAILURE: CLASS UNKNOWN")
    END SELECT

    IOFF = IOFF + ILEN

  ENDDO

  IF (JPASS == 1) THEN
    ALLOCATE (LG (IOFF))
  ENDIF

ENDDO

END FUNCTION LG

FUNCTION LS1RB (YLF, NAME,LDACC)
! Creation of a SPEC_VIEW encapsulating a FIELD_1RB field
CLASS (FIELD_1RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
LOGICAL, OPTIONAL :: LDACC

CHARACTER(LEN=6) CLOUT
TYPE (SPEC_VIEW), ALLOCATABLE :: LS1RB (:)

REAL(KIND=JPRB), POINTER :: ZZ1 (:)
LOGICAL :: LLACC = .FALSE.

IF (PRESENT(LDACC)) THEN
  LLACC = LDACC
END IF

IF (LLACC) THEN
  ZZ1 => GET_DEVICE_DATA_RDWR(YLF)
ELSE
  ZZ1 => GET_HOST_DATA_RDWR(YLF)
ENDIF

ALLOCATE (LS1RB (1))

LS1RB (1)%VIEW%P => ZZ1
LS1RB(1)%NAME=TRIM(NAME)//TRIM(CLOUT)

END FUNCTION

FUNCTION LS2RB (YLF,NAME,LDACC)
! Creation of a list of SPEC_VIEW, each of them encapsulating a layer of an input FIELD_2RB field.
! Given YLF dimensioned(NSPEC, NLEVS) as input,
! the output list size will contain (NLEVS) elements dimensioned(NSPEC)
CLASS (FIELD_2RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
LOGICAL, OPTIONAL :: LDACC

CHARACTER(LEN=6) CLOUT
TYPE (SPEC_VIEW), ALLOCATABLE :: LS2RB (:)

REAL(KIND=JPRB), POINTER :: ZZ2 (:,:)
INTEGER(KIND=JPIM) :: I1, J
LOGICAL :: LLACC = .FALSE.

IF (PRESENT(LDACC)) THEN
  LLACC = LDACC
END IF

IF (LLACC) THEN
  ZZ2 => GET_DEVICE_DATA_RDWR(YLF)
ELSE
  ZZ2 => GET_HOST_DATA_RDWR(YLF)
ENDIF
ALLOCATE (LS2RB (SIZE (ZZ2, 1)))

J = 1

DO I1 = LBOUND (ZZ2, 1), UBOUND (ZZ2, 1)
  LS2RB (J)%VIEW%P => ZZ2 (I1, :)
  LS2RB(J)%NAME=TRIM(NAME)//TRIM(CLOUT)
  J = J + 1
ENDDO

END FUNCTION

FUNCTION LS3RB (YLF,NAME,LDACC)
! Creation of a list of SPEC_VIEW, each of them encapsulating a layer of an input FIELD_3RB field.
! Given YLF dimensioned(NPROMA, NLEVS, NBLKS) as input,
! the output list size will contain (NLEVS) SPEC_VIEW, each of them dimensioned(NPROMA, NBLKS)
  CLASS (FIELD_3RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
LOGICAL, OPTIONAL :: LDACC

CHARACTER(LEN=6) CLOUT
TYPE (SPEC_VIEW), ALLOCATABLE :: LS3RB (:)

REAL(KIND=JPRB), POINTER :: ZZ3 (:,:,:)
INTEGER(KIND=JPIM) :: I1, I3, J
LOGICAL :: LLACC = .FALSE.

IF (PRESENT(LDACC)) THEN
  LLACC = LDACC
END IF

IF (LLACC) THEN
  ZZ3 => GET_DEVICE_DATA_RDWR(YLF)
ELSE
  ZZ3 => GET_HOST_DATA_RDWR(YLF)
ENDIF

ALLOCATE (LS3RB (SIZE (ZZ3, 1) * SIZE (ZZ3, 3)))

J = 1

DO I3 = LBOUND (ZZ3, 3), UBOUND (ZZ3, 3)
  DO I1 = LBOUND (ZZ3, 1), UBOUND (ZZ3, 1)
    LS3RB (J)%VIEW%P => ZZ3 (I1, :, I3)
    LS3RB(J)%NAME=TRIM(NAME)//TRIM(CLOUT)
    J = J + 1
  ENDDO
ENDDO

END FUNCTION

FUNCTION LS4RB (YLF, NAME,LDACC)
! Creation of a list of SPEC_VIEW, each of them encapsulating a layer of an input FIELD_4RB field.
! Given YLF dimensioned(NPROMA, NLEVS, NFLDS, NBLKS) as input,
! the output list size will contain (NLEVS * NFLDS) SPEC_VIEW, each of them dimensioned(NPROMA, NBLKS)
CLASS (FIELD_4RB), POINTER, INTENT (IN) :: YLF
CHARACTER(LEN=*) ::NAME
LOGICAL, OPTIONAL :: LDACC

CHARACTER(LEN=6) CLOUT
TYPE (SPEC_VIEW), ALLOCATABLE :: LS4RB (:)

REAL(KIND=JPRB), POINTER :: ZZ4 (:,:,:,:)
INTEGER(KIND=JPIM) :: I1, I3, I4,  J
LOGICAL :: LLACC = .FALSE.

IF (PRESENT(LDACC)) THEN
  LLACC = LDACC
END IF

IF (LLACC) THEN
  ZZ4 => GET_DEVICE_DATA_RDWR(YLF)
ELSE
  ZZ4 => GET_HOST_DATA_RDWR(YLF)
ENDIF

ALLOCATE (LS4RB (SIZE (ZZ4, 1) * SIZE (ZZ4, 3) * SIZE (ZZ4, 4)))

J = 1

DO I4 = LBOUND (ZZ4, 4), UBOUND (ZZ4, 4)
  DO I3 = LBOUND (ZZ4, 3), UBOUND (ZZ4, 3)
    DO I1 = LBOUND (ZZ4, 1), UBOUND (ZZ4, 1)
      LS4RB (J)%VIEW%P => ZZ4 (I1, :, I3, I4)
      LS4RB(J)%NAME=TRIM(NAME)//TRIM(CLOUT)
      J = J + 1
    ENDDO
  ENDDO
ENDDO

END FUNCTION

FUNCTION LS (YLFL, LDACC)
! Creation of a list of SPEC_VIEW from a list  YLFL of FIELD_BASIC_PTR
TYPE (SPEC_VIEW), ALLOCATABLE :: LS (:)
LOGICAL, OPTIONAL :: LDACC

TYPE (FIELD_BASIC_PTR) :: YLFL (:)
INTEGER(KIND=JPIM) :: IOFF, ILEN, JFLD, JPASS
INTEGER(KIND=JPIM) :: ILBOUNDS (5), IUBOUNDS (5)

! First pass: determination of the output size list
! Second pass: allocate and instanciate the SPEC_VIEW types
DO JPASS = 1, 2
  
  IOFF = 0
  ILEN = -1

  ! iterate over YLFL LIST
  DO JFLD = 1, SIZE (YLFL)

   ! Phase 1: compute number of field_view that will be generated for each field of the list
   ! Phase 2: call the correct routine to create the SPEC_VIEW for each field of the list
    SELECT TYPE (YLF => YLFL (JFLD)%PTR)
      CLASS IS (FIELD_1RB)
        ILEN = 1
        IF (JPASS == 2) LS (IOFF+1:IOFF+ILEN) = LS1RB (YLF,YLFL(JFLD)%NAME, LDACC)
      CLASS IS (FIELD_2RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
        ILEN = (IUBOUNDS (1) - ILBOUNDS (1) + 1)
        IF (JPASS == 2) LS (IOFF+1:IOFF+ILEN) = LS2RB (YLF,YLFL(JFLD)%NAME, LDACC)
      CLASS IS (FIELD_3RB)
        CALL YLF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)
         ILEN =  (IUBOUNDS (1) - ILBOUNDS (1) + 1)* (IUBOUNDS (3) - ILBOUNDS (3) + 1)
        IF (JPASS == 2) LS (IOFF+1:IOFF+ILEN) = LS3RB (YLF ,YLFL(JFLD)%NAME,LDACC)
      CLASS IS (FIELD_4RB)
          CALL ABOR1("LS not implemeted for field_4rb")
      CLASS DEFAULT
         ! Skip the spectral field as it is not present on this processor
         ILEN = 1
    END SELECT

    IOFF = IOFF + ILEN

  ENDDO

  ! at the end of the first pass, allocation of the list of SPEC_VIEW
  IF (JPASS == 1) THEN
    ALLOCATE (LS (IOFF))
  ENDIF

ENDDO

END FUNCTION LS

END MODULE FIELD_API_ECTRANS_MOD

