INTERFACE

SUBROUTINE INV_TRANS_FIELD_API(YDFSPVOR,YDFSPDIV,YDFSPSCALAR, &
                             & YDFU, YDFV, YDFVOR,YDFDIV,YDFSCALAR, &
                             & YDFUDM, YDFVDM, YDFSCALARDM, YDFSCALARDL,& 
                             & KSPEC, KPROMA, KGPBLKS, KGPTOT, KFLEVG, KFLEVL,&
                             & LDACC, LDVERBOSE, &
                             & FSPGL_PROC)

USE FIELD_API_BASIC_TYPE_MOD, ONLY: FIELD_BASIC_PTR
USE PARKIND1  , ONLY : JPIM, JPRB
                                                     
                             
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPVOR(:), YDFSPDIV(:)        ! SPECTRAL VECTOR FIELDS : VORTICITY AND DIVERGENCE FIELDS (IN)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPSCALAR(:)                  ! SPECTRAL SCALAR FIELDS (IN)

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFU(:),YDFV(:)                 ! GRID VECTOR FIELDS     (OUT)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFVOR(:),YDFDIV(:)             ! GRID VECTOR FIELDS :VORTICITY AND DIVERGENCE     (OUT)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSCALAR(:)                    ! GRID SCALAR FIELDS     (OUT)

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFUDM(:),YDFVDM(:)             ! GRID VECTOR FIELDS DERIVATIVES EW (OUT)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSCALARDM(:), YDFSCALARDL(:)  ! GRID SCALAR FIELDS DERIVATIVES EW AND NS (OUT)

INTEGER(KIND=JPIM),   INTENT(IN)            :: KSPEC
INTEGER(KIND=JPIM),   INTENT(IN)            :: KPROMA
INTEGER(KIND=JPIM),   INTENT(IN)            :: KGPBLKS
INTEGER(KIND=JPIM),   INTENT(IN)            :: KGPTOT
INTEGER(KIND=JPIM),   INTENT(IN)            :: KFLEVG
INTEGER(KIND=JPIM),   INTENT(IN)            :: KFLEVL
LOGICAL,              INTENT(IN), OPTIONAL  :: LDACC
LOGICAL,              INTENT(IN), OPTIONAL  :: LDVERBOSE
PROCEDURE (FSPGL_INTF),           OPTIONAL  :: FSPGL_PROC

END SUBROUTINE INV_TRANS_FIELD_API

END INTERFACE
