SUBROUTINE DIR_TRANS_FIELD_API(YDFSPVOR,YDFSPDIV,YDFSPSCALAR, &
                             & YDFU, YDFV, YDFVOR,YDFDIV,YDFSCALAR, &
                             & KSPEC, KPROMA, KGPBLKS, KGPTOT, KFLEVG, KFLEVL,&
                             & LDACC, LDVERBOSE)


USE FIELD_API_BASIC_TYPE_MOD, ONLY: FIELD_BASIC_PTR
USE FIELD_API_ECTRANS_MOD
USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPVOR(:), YDFSPDIV(:)        !SPECTRAL VECTOR FIELDS : VORTICITY AND DIVERGENCE FIELDS (IN)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPSCALAR(:)                !SPECTRAL SCALAR FIELDS (IN)

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFU(:),YDFV(:)                 !GRID VECTOR FIELDS     (OUT)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFVOR(:),YDFDIV(:)             !GRID VECTOR FIELDS :VORTICITY AND DIVERGENCE     (OUT)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSCALAR(:)                  !GRID SCALAR FIELDS     (OUT)

INTEGER(KIND=JPIM), INTENT(IN) ::KSPEC
INTEGER(KIND=JPIM), INTENT(IN) ::KPROMA
INTEGER(KIND=JPIM), INTENT(IN) ::KGPBLKS
INTEGER(KIND=JPIM), INTENT(IN) ::KGPTOT
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVL
LOGICAL, INTENT(IN), OPTIONAL  :: LDACC
LOGICAL, INTENT(IN), OPTIONAL  :: LDVERBOSE

! LOCAL VARIABLES

! TEMPORARY ARRAYS:

TYPE(SPEC_VIEW), ALLOCATABLE  :: YLSPVVOR(:), YLSPVDIV(:)
TYPE(SPEC_VIEW), ALLOCATABLE  :: YLSPVSCALAR(:)

TYPE(GRID_VIEW), ALLOCATABLE  :: YLGVU(:),YLGVV(:)
TYPE(GRID_VIEW), ALLOCATABLE  :: YLGVVOR(:),YLGVDIV(:)
TYPE(GRID_VIEW), ALLOCATABLE  :: YLGVSCALAR(:)

REAL(KIND=JPRB),ALLOCATABLE :: ZPSPVOR(:,:),ZPSPDIV(:,:)          ! SPECTRAL VECTOR FIELDS (IN)
REAL(KIND=JPRB),ALLOCATABLE :: ZPSPSC2(:,:)                       ! SPECTRAL SURFACE SCALAR FIELDS(IN)
REAL(KIND=JPRB),ALLOCATABLE :: ZPGPUV(:,:,:,:)                    ! GRID VECTOR FIELDS (OUT)
REAL(KIND=JPRB),ALLOCATABLE :: ZPGP2(:,:,:)                       ! GRID SURFACE SCALAR FIELDS (OUT)

INTEGER(KIND=JPIM)          :: ISPUV                              ! NUMBER OF INPUT SPECTRAL VECTOR FIELDS
INTEGER(KIND=JPIM)          :: IFLDXG
INTEGER(KIND=JPIM)          :: IFLDXL
INTEGER(KIND=JPIM)          :: IFLDXGUV
INTEGER(KIND=JPIM)          :: IFLDXLUV
INTEGER(KIND=JPIM)          :: IUVG                               ! NUMBER OF OUTPUT VECTOR FIELDS
INTEGER(KIND=JPIM)          :: ISCDIM                             ! SIZE OF OUTPUT SCALAR FIELDS ARRAY
INTEGER(KIND=JPIM)          :: IUVDIM                             ! SIZE OF OUTPUT VECTOR FIELDS ARRAY
INTEGER(KIND=JPIM)          :: ID,IOFFSET,JLEV
INTEGER(KIND=JPIM)          :: IEND


INTEGER(KIND=JPIM),ALLOCATABLE :: IVSETUV(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IVSETSC2(:)

INTEGER(KIND=JPIM)          :: JFLD                                 ! FIELD COUNTER
LOGICAL          :: LLSCDERS                                        ! INDICATING IF DERIVATIVES OF SCALAR VARIABLES ARE REQ.
LOGICAL          :: LLVORGP                                         ! INDICATING IF GRID-POINT VORTICITY IS REQ.
LOGICAL          :: LLDIVGP                                         ! INDICATING IF GRID-POINT DIVERGENCE IS REQ.
LOGICAL          :: LLUVDER                                         ! INDICATING IF E-W DERIVATIVES OF U AND V ARE REQ.
LOGICAL          :: LLVERBOSE                                       ! INDICATING IF VERBOSE OUTPUT IS REQ.
#include "dir_trans.h"
#include "abor1.intfb.h"

LLVERBOSE = .FALSE.
IF (PRESENT(LDVERBOSE))  LLVERBOSE = LDVERBOSE

! 1. VECTOR FIELDS TRANSFORMATION

! CHECK IF ALL PROVIDED VECTOR FIELD INFORMATION IS CONSISTENT
IF (PRESENT(YDFU) .NEQV. PRESENT(YDFV)) CALL ABOR1("[ECTRANS_API] IYDU/YDFV")
IF (PRESENT(YDFU) .NEQV. PRESENT(YDFSPVOR)) CALL ABOR1("[ECTRANS_API] IYDU/YDFVOR")
IF (PRESENT(YDFU) .NEQV. PRESENT(YDFSPDIV)) CALL ABOR1("[ECTRANS_API] IYDU/YDFDIV")

IUVDIM = 0
! DO WE HAVE VECTOR FIELDS?

IF (PRESENT(YDFU)) THEN

  IF ((SIZE(YDFU)/= SIZE(YDFV)).OR.(SIZE(YDFU)/= SIZE(YDFSPDIV)).OR.(SIZE(YDFU)/= SIZE(YDFSPVOR))) THEN
     CALL ABOR1("[ECTRANS_API] INVALID LIST SIZES:")
  ENDIF
  YLSPVVOR = LS (YDFSPVOR, LDACC)
  YLSPVDIV = LS (YDFSPDIV, LDACC)

  YLGVU = LG (YDFU, LDACC)
  YLGVV = LG (YDFV, LDACC)
  IF ((SIZE (YLGVU) /= SIZE (YLGVV)) .OR. (SIZE (YLSPVVOR) /= SIZE (YLSPVDIV))) THEN
     CALL ABOR1("[ECTRANS_API] INCONSISTENT NUMBER OF FIELD_VIEW FOR VECTORS:")
  ENDIF
   IF (((SIZE (YLGVU) / SIZE (YDFU)) /= KFLEVG) .OR. ((SIZE (YLSPVVOR) / SIZE (YDFSPVOR)) /= KFLEVL)) THEN
     CALL ABOR1("[ECTRANS_API] INCONSISTENT KFLEVG OR KFLEVL")
  ENDIF

  IUVG = SIZE(YDFU)           ! NUMBER OF OUTPUT  VECTOR FIELDS
  ISPUV = SIZE(YDFSPVOR)

  IUVDIM = 2

  IF (PRESENT(YDFDIV)) THEN
     LLDIVGP = .TRUE.
     IUVDIM = 5
     YLGVDIV = LG (YDFDIV, LDACC)
  ENDIF

  IF (PRESENT(YDFVOR)) THEN
     LLVORGP = .TRUE.
     IUVDIM = 6
     YLGVVOR = LG (YDFVOR, LDACC)
  ENDIF
   
  ! ALLOCATE VECTOR FIELD INPUT IN SPECTRAL SPACE
  ALLOCATE(ZPSPVOR(SIZE(YLSPVVOR),KSPEC))
  ALLOCATE(ZPSPDIV(SIZE(YLSPVDIV),KSPEC))

  ! ALLOCATE VECTOR FIELD OUTPUT IN GRID SPACE
  ALLOCATE(ZPGPUV(KPROMA,KFLEVG, IUVG * IUVDIM,KGPBLKS))
  ALLOCATE(IVSETUV(KFLEVG))

  ! COPY FROM FIELDS TO TEMPORARY ARRAYS (1D COPY THANKS TO FIELD VIEW)

  DO JFLD=1,SIZE(YLSPVVOR)
     ZPSPVOR(JFLD,:) = YLSPVVOR(JFLD)%VIEW%P(:)
     ZPSPDIV(JFLD,:) = YLSPVDIV(JFLD)%VIEW%P(:)
  ENDDO


ELSE
  ! YDFU IS NOT PROVIDED, WE DO NOT HAVE TO COMPUTE THE CORRESPONDING VECTOR OUTPUT
  ISPUV = 0
  ALLOCATE(ZPGPUV(0,ISPUV,2,0),ZPSPVOR(0,0),ZPSPDIV(0,0))
ENDIF

! 2. SCALAR FIELDS TRANSFORMATION

! CHECK IF ALL PROVIDED SCALAR FIELD INFORMATION IS CONSISTENT
IF (PRESENT(YDFSPSCALAR) .NEQV. PRESENT(YDFSCALAR))  CALL ABOR1("[ECTRANS_API] GRID/SPEC")

IF (PRESENT(YDFSPSCALAR)) THEN

  IF ((SIZE(YDFSPSCALAR)/= SIZE(YDFSCALAR)))  CALL ABOR1("[ECTRANS_API] INCONSISTENT NUMBER OF FIELD_VIEW FOR YDFSCALAR")

  YLGVSCALAR = LG (YDFSCALAR, LDACC)
  YLSPVSCALAR = LS (YDFSPSCALAR, LDACC)

  IFLDXG = SIZE(YLGVSCALAR) ! NUMBER OF OUTPUT SCALAR FIELDS IN GRID SPACE

  IFLDXL = 0  ! NUMBER OF INPUT SCALAR FIELDS IN SPECTRAL SPACE
  DO JFLD = 1, SIZE(YLGVSCALAR) ! NUMBER OF OUTPUT SCALAR FIELDS IN GRID SPACE
  IF (ASSOCIATED(YLSPVSCALAR(JFLD)%VIEW%P)) IFLDXL = IFLDXL + 1
  END DO 

  ISCDIM = 1

   ! ALLOCATE SCALAR FIELD INPUT IN SPECTRAL SPACE
  ALLOCATE(ZPSPSC2(IFLDXL,KSPEC))

  ! ALLOCATE SCALAR FIELD OUTPUT IN GRID SPACE
  ALLOCATE(ZPGP2(KPROMA,IFLDXG * ISCDIM,KGPBLKS))
  ALLOCATE(IVSETSC2(IFLDXG))

 ! COPY SCALAR SPECTRAL FIELDS TO TEMPORARY ARRAYS (1D COPY THANKS TO FIELD VIEW)
  ID = 1
  DO JFLD = 1, SIZE(YLSPVSCALAR) ! NUMBER OF OUTPUT SCALAR FIELDS IN GRID SPACE
     IF (ASSOCIATED(YLSPVSCALAR(JFLD)%VIEW%P)) THEN
         ZPSPSC2(ID,:) = YLSPVSCALAR(JFLD)%VIEW%P(:)
         ID = ID + 1 
     ENDIF
  ENDDO

 DO JFLD=1, IFLDXG
    IVSETSC2(JFLD) = YLGVSCALAR(JFLD)%IVSET
 ENDDO


DO JFLD=1,IUVG
  DO JLEV=1,KFLEVG
     ID = JLEV + (JFLD -1) * KFLEVG
     IF (JFLD .EQ. 1) IVSETUV(JLEV) = YLGVU(ID)%IVSET
     IF (IVSETUV(JLEV) .NE. YLGVU(ID)%IVSET)  CALL ABOR1("[ECTRANS_API] IVSETUV INCONSISTENT WITH YLGVU%IVSET")
     IF (IVSETUV(JLEV) .NE. YLGVV(ID)%IVSET)  CALL ABOR1("[ECTRANS_API] IVSETUV INCONSISTENT WITH YLGVV%IVSET")
  ENDDO
ENDDO
!
ELSE
  IFLDXG = 0
  ALLOCATE(ZPGP2(0,IFLDXG,0),ZPSPSC2(0,1))
ENDIF


! 3. CALL DIR_TRANS

	CALL DIR_TRANS(PSPVOR = ZPSPVOR,PSPDIV = ZPSPDIV,PGPUV = ZPGPUV,KVSETUV = IVSETUV, &
	             & PSPSC2 = ZPSPSC2,PGP2 = ZPGP2, KVSETSC2 = IVSETSC2, &
	             & KPROMA = KPROMA)
! 4. COPY BACK DATA TO FIELDS

! REMOVE GARBAGE AT THE END OF ARRAYS
  IEND = KGPTOT - KPROMA * (KGPBLKS - 1)
  ZPGPUV (IEND+1:, :, :, KGPBLKS) = 0
  ZPGP2 (IEND+1:, :, KGPBLKS) = 0

  ! COPY VECTOR FIELDS BACK FROM TEMPORARY VECTOR ARRAYS
IOFFSET = 0

IF (LLVORGP) THEN
  DO JFLD=1,IUVG
    DO JLEV=1,KFLEVG
     ID = JLEV + (JFLD -1) * KFLEVG
     YLGVVOR(ID)%VIEW%P(:,:) = ZPGPUV(:, JLEV,JFLD+IOFFSET*IUVG,:)
    ENDDO
  ENDDO
  IOFFSET = IOFFSET + 1
ENDIF

IF (LLDIVGP) THEN
  DO JFLD=1,IUVG
    DO JLEV=1,KFLEVG
     ID = JLEV + (JFLD -1) * KFLEVG
     YLGVDIV(ID)%VIEW%P(:,:) = ZPGPUV(:, JLEV,JFLD+IOFFSET*IUVG,:)
    ENDDO
  ENDDO
  IOFFSET = IOFFSET + 1
ENDIF

DO JFLD=1,IUVG
  DO JLEV=1,KFLEVG
     ID = JLEV + (JFLD -1) * KFLEVG
     YLGVU(ID)%VIEW%P(:,:) =  ZPGPUV(:,JLEV,JFLD+IOFFSET*IUVG,:)
     YLGVV(ID)%VIEW%P(:,:) =  ZPGPUV(:,JLEV,JFLD+(IOFFSET+1)*IUVG,:)
  ENDDO
ENDDO

! COPY SCALAR FIELDS BACK FROM TEMPORARY SCALAR ARRAYS
DO JFLD=1, IFLDXG
    YLGVSCALAR(JFLD)%VIEW%P(:,:) = ZPGP2(:,JFLD,:)
ENDDO


DEALLOCATE(ZPSPVOR)
DEALLOCATE(ZPSPDIV)
DEALLOCATE(ZPSPSC2)
DEALLOCATE(ZPGPUV)
DEALLOCATE(ZPGP2)
DEALLOCATE(IVSETUV)
DEALLOCATE(IVSETSC2)

END SUBROUTINE DIR_TRANS_FIELD_API


