SUBROUTINE DIR_TRANS_FIELD_API(YDFSPVOR,YDFSPDIV,YDFSPSCALAR, &
                             & YDFU, YDFV, YDFSCALAR, &
                             & KSPEC, KPROMA, KGPBLKS, KGPTOT, KFLEVG, KFLEVL,&
                             & LDACC)


USE FIELD_API_BASIC_TYPE_MOD, ONLY: FIELD_BASIC_PTR
USE FIELD_API_ECTRANS_MOD
USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPVOR(:), YDFSPDIV(:)        !SPECTRAL VECTOR FIELDS : VORTICITY AND DIVERGENCE FIELDS (IN)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPSCALAR(:)                !SPECTRAL SCALAR FIELDS (IN)

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFU(:),YDFV(:)                 !GRID VECTOR FIELDS     (OUT)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSCALAR(:)                  !GRID SCALAR FIELDS     (OUT)

INTEGER(KIND=JPIM), INTENT(IN) ::KSPEC
INTEGER(KIND=JPIM), INTENT(IN) ::KPROMA
INTEGER(KIND=JPIM), INTENT(IN) ::KGPBLKS
INTEGER(KIND=JPIM), INTENT(IN) ::KGPTOT
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVL
LOGICAL, INTENT(IN), OPTIONAL  :: LDACC

! LOCAL VARIABLES

! TEMPORARY ARRAYS:

TYPE(SPEC_VIEW), ALLOCATABLE  :: YLSPVVOR(:), YLSPVDIV(:)
TYPE(SPEC_VIEW), ALLOCATABLE  :: YLSPVSCALAR(:)

TYPE(GRID_VIEW), ALLOCATABLE  :: YLGVU(:),YLGVV(:)
TYPE(GRID_VIEW), ALLOCATABLE  :: YLGVSCALAR(:)

REAL(KIND=JPRB),POINTER :: ZPSPVOR(:,:),ZPSPDIV(:,:)          ! SPECTRAL VECTOR FIELDS (IN)
REAL(KIND=JPRB),POINTER :: ZPSPSC2(:,:)                       ! SPECTRAL SURFACE SCALAR FIELDS(IN)
REAL(KIND=JPRB),POINTER :: ZPGPUV(:,:,:,:)                    ! GRID VECTOR FIELDS (OUT)
REAL(KIND=JPRB),POINTER :: ZPGP2(:,:,:)                       ! GRID SURFACE SCALAR FIELDS (OUT)

INTEGER(KIND=JPIM)          :: ISPUV = 0                             ! NUMBER OF INPUT SPECTRAL VECTOR FIELDS
INTEGER(KIND=JPIM)          :: IFLDXG  = 0
INTEGER(KIND=JPIM)          :: IFLDXL = 0
INTEGER(KIND=JPIM)          :: IFLDXGUV = 0
INTEGER(KIND=JPIM)          :: IFLDXLUV = 0
INTEGER(KIND=JPIM)          :: IUVG = 0                               ! NUMBER OF OUTPUT VECTOR FIELDS
INTEGER(KIND=JPIM)          :: ISCDIM = 0                             ! SIZE OF OUTPUT SCALAR FIELDS ARRAY
INTEGER(KIND=JPIM)          :: IUVDIM = 0                             ! SIZE OF OUTPUT VECTOR FIELDS ARRAY
INTEGER(KIND=JPIM)          :: ID = 0,IOFFSET,JLEV = 0
INTEGER(KIND=JPIM)          :: IEND = 0


INTEGER(KIND=JPIM),ALLOCATABLE :: IVSETUV(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IVSETSC2(:)

INTEGER(KIND=JPIM)          :: JFLD  = 0                                ! FIELD COUNTER
#include "dir_trans.h"
#include "abor1.intfb.h"


! 1. VECTOR FIELDS TRANSFORMATION

! CHECK IF ALL PROVIDED VECTOR FIELD INFORMATION IS CONSISTENT
IF (PRESENT(YDFU) .NEQV. PRESENT(YDFV)) CALL ABOR1("[ECTRANS_API] IYDU/YDFV")
!IF (PRESENT(YDFU) .NEQV. PRESENT(YDFSPVOR)) CALL ABOR1("[ECTRANS_API] IYDU/YDFVOR")
!IF (PRESENT(YDFU) .NEQV. PRESENT(YDFSPDIV)) CALL ABOR1("[ECTRANS_API] IYDU/YDFDIV")

IUVDIM = 0
! DO WE HAVE VECTOR FIELDS?

IF (PRESENT(YDFU)) THEN

  IF ((SIZE(YDFU)/= SIZE(YDFV)).OR.(SIZE(YDFU)/= SIZE(YDFSPDIV)).OR.(SIZE(YDFU)/= SIZE(YDFSPVOR))) THEN
     CALL ABOR1("[ECTRANS_API] INVALID LIST SIZES:")
  ENDIF
  YLSPVVOR = LS (YDFSPVOR, LDACC)
  YLSPVDIV = LS (YDFSPDIV, LDACC)

  YLGVU = LG (YDFU, LDACC)
  YLGVV = LG (YDFV, LDACC)
  IF ((SIZE (YLGVU) /= SIZE (YLGVV)) .OR. (SIZE (YLSPVVOR) /= SIZE (YLSPVDIV))) THEN
     CALL ABOR1("[ECTRANS_API] INCONSISTENT NUMBER OF FIELD_VIEW FOR VECTORS:")
  ENDIF
   IF (((SIZE (YLGVU) / SIZE (YDFU)) /= KFLEVG) .OR. ((SIZE (YLSPVVOR) / SIZE (YDFSPVOR)) /= KFLEVL)) THEN
     CALL ABOR1("[ECTRANS_API] INCONSISTENT KFLEVG OR KFLEVL")
  ENDIF

  IUVG = SIZE(YDFU)           ! NUMBER OF OUTPUT  VECTOR FIELDS
  ISPUV = SIZE(YDFSPVOR)

  IUVDIM = 2
   
  ! ALLOCATE VECTOR FIELD INPUT IN SPECTRAL SPACE
  ALLOCATE(ZPSPVOR(SIZE(YLSPVVOR),KSPEC))
  ALLOCATE(ZPSPDIV(SIZE(YLSPVDIV),KSPEC))

  ! ALLOCATE VECTOR FIELD OUTPUT IN GRID SPACE
  ALLOCATE(ZPGPUV(KPROMA,KFLEVG, IUVG * IUVDIM,KGPBLKS))
  ALLOCATE(IVSETUV(KFLEVG))


  IOFFSET = 0

  DO JFLD=1,IUVG
    DO JLEV=1,KFLEVG
       ID = JLEV + (JFLD -1) * KFLEVG
       ZPGPUV(:,JLEV,JFLD+IOFFSET*IUVG,:) = YLGVU(ID)%VIEW%P(:,:) 
       ZPGPUV(:,JLEV,JFLD+(IOFFSET+1)*IUVG,:) = YLGVV(ID)%VIEW%P(:,:) 
       IF (JFLD .EQ. 1) IVSETUV(JLEV) = YLGVU(ID)%IVSET
       IF (IVSETUV(JLEV) .NE. YLGVU(ID)%IVSET)  CALL ABOR1("[ECTRANS_API] IVSETUV INCONSISTENT WITH YLGVU%IVSET")
    ENDDO
  ENDDO
    
ELSE
  ! YDFU IS NOT PROVIDED, WE DO NOT HAVE TO COMPUTE THE CORRESPONDING VECTOR OUTPUT
  ISPUV = 0
  ZPGPUV=>NULL()  
  ZPSPVOR=>NULL()
  ZPSPDIV=>NULL()
ENDIF

! 2. SCALAR FIELDS TRANSFORMATION

! CHECK IF ALL PROVIDED SCALAR FIELD INFORMATION IS CONSISTENT
IF (PRESENT(YDFSPSCALAR) .NEQV. PRESENT(YDFSCALAR))  CALL ABOR1("[ECTRANS_API] GRID/SPEC")

IF (PRESENT(YDFSPSCALAR)) THEN

  IF ((SIZE(YDFSPSCALAR)/= SIZE(YDFSCALAR)))  CALL ABOR1("[ECTRANS_API] INCONSISTENT NUMBER OF FIELD_VIEW FOR YDFSCALAR")

  YLGVSCALAR = LG (YDFSCALAR, LDACC)
  YLSPVSCALAR = LS (YDFSPSCALAR, LDACC)

  IFLDXG = SIZE(YLGVSCALAR) ! NUMBER OF OUTPUT SCALAR FIELDS IN GRID SPACE

  IFLDXL = 0  ! NUMBER OF INPUT SCALAR FIELDS IN SPECTRAL SPACE
  DO JFLD = 1, SIZE(YLGVSCALAR) ! NUMBER OF OUTPUT SCALAR FIELDS IN GRID SPACE
  IF (ASSOCIATED(YLSPVSCALAR(JFLD)%VIEW%P)) IFLDXL = IFLDXL + 1
  END DO 

  ISCDIM = 1

   ! ALLOCATE SCALAR FIELD INPUT IN SPECTRAL SPACE
  ALLOCATE(ZPSPSC2(IFLDXL,KSPEC))

  ! ALLOCATE SCALAR FIELD OUTPUT IN GRID SPACE
  ALLOCATE(ZPGP2(KPROMA,IFLDXG * ISCDIM,KGPBLKS))
  ALLOCATE(IVSETSC2(IFLDXG))

 DO JFLD=1, IFLDXG
  ZPGP2(:,JFLD,:) = YLGVSCALAR(JFLD)%VIEW%P(:,:)
  IVSETSC2(JFLD) = YLGVSCALAR(JFLD)%IVSET
ENDDO

!
ELSE
  IFLDXG = 0
  ZPGP2=>NULL()
  ZPSPSC2=>NULL()  
ENDIF


! 3. CALL DIR_TRANS

	CALL DIR_TRANS(PSPVOR = ZPSPVOR,PSPDIV = ZPSPDIV,PGPUV = ZPGPUV,KVSETUV = IVSETUV, &
	             & PSPSC2 = ZPSPSC2,PGP2 = ZPGP2, KVSETSC2 = IVSETSC2, &
	             & KPROMA = KPROMA)
! 4. COPY BACK DATA TO FIELDS

! REMOVE GARBAGE AT THE END OF ARRAYS
  IEND = KGPTOT - KPROMA * (KGPBLKS - 1)
!  ZPGPUV (IEND+1:, :, :, KGPBLKS) = 0
 ! ZPGP2 (IEND+1:, :, KGPBLKS) = 0

  IF (IUVG>0) THEN
    DO JFLD=1,SIZE(YLSPVVOR)
      YLSPVVOR(JFLD)%VIEW%P(:) = ZPSPVOR(JFLD,:)  
      YLSPVDIV(JFLD)%VIEW%P(:) = ZPSPDIV(JFLD,:)
   ENDDO
 ENDIF



 ID = 1
 DO JFLD = 1, SIZE(YLSPVSCALAR) ! NUMBER OF OUTPUT SCALAR FIELDS IN GRID SPACE
    IF (ASSOCIATED(YLSPVSCALAR(JFLD)%VIEW%P)) THEN
      YLSPVSCALAR(JFLD)%VIEW%P(:) = ZPSPSC2(ID,:) 
        ID = ID + 1 
    ENDIF
 ENDDO

IF (ASSOCIATED(ZPSPVOR)) DEALLOCATE(ZPSPVOR)
IF (ASSOCIATED(ZPSPDIV)) DEALLOCATE(ZPSPDIV)
IF (ASSOCIATED(ZPSPSC2)) DEALLOCATE(ZPSPSC2)
IF (ASSOCIATED(ZPGPUV)) DEALLOCATE(ZPGPUV)
IF (ASSOCIATED(ZPGP2)) DEALLOCATE(ZPGP2)
IF (ALLOCATED(IVSETUV)) DEALLOCATE(IVSETUV)
IF (ALLOCATED(IVSETSC2)) DEALLOCATE(IVSETSC2)

END SUBROUTINE DIR_TRANS_FIELD_API


