!! spectral to grid space transformation
SUBROUTINE INV_TRANS_FIELD_API(YDFSPVOR,YDFSPDIV,YDFSPSCALAR, &
                             & YDFU, YDFV, YDFVOR,YDFDIV,YDFSCALAR, &
                             & YDFUDM, YDFVDM, YDFSCALARDM, YDFSCALARDL,& 
                             & KSPEC, KPROMA, KGPBLKS, KGPTOT, KFLEVG, KFLEVL,&
                             & LDACC, LDVERBOSE, &
                             & FSPGL_PROC)

USE FIELD_API_BASIC_TYPE_MOD, ONLY: FIELD_BASIC_PTR
USE FIELD_API_ECTRANS_MOD
USE PARKIND1  , ONLY : JPIM, JPRB

IMPLICIT NONE

#include "fspgl_intf.h"

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPVOR(:), YDFSPDIV(:)        ! SPECTRAL VECTOR FIELDS : VORTICITY AND DIVERGENCE FIELDS (IN)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPSCALAR(:)                  ! SPECTRAL SCALAR FIELDS (IN)

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFU(:),YDFV(:)                 ! GRID VECTOR FIELDS     (OUT)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFVOR(:),YDFDIV(:)             ! GRID VECTOR FIELDS :VORTICITY AND DIVERGENCE     (OUT)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSCALAR(:)                    ! GRID SCALAR FIELDS     (OUT)

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFUDM(:),YDFVDM(:)             ! GRID VECTOR FIELDS DERIVATIVES EW (OUT)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSCALARDM(:), YDFSCALARDL(:)  ! GRID SCALAR FIELDS DERIVATIVES EW AND NS (OUT)

INTEGER(KIND=JPIM),   INTENT(IN)            :: KSPEC
INTEGER(KIND=JPIM),   INTENT(IN)            :: KPROMA
INTEGER(KIND=JPIM),   INTENT(IN)            :: KGPBLKS
INTEGER(KIND=JPIM),   INTENT(IN)            :: KGPTOT
INTEGER(KIND=JPIM),   INTENT(IN)            :: KFLEVG
INTEGER(KIND=JPIM),   INTENT(IN)            :: KFLEVL
LOGICAL,              INTENT(IN), OPTIONAL  :: LDACC
LOGICAL,              INTENT(IN), OPTIONAL  :: LDVERBOSE
PROCEDURE (FSPGL_INTF),           OPTIONAL  :: FSPGL_PROC

#include "inv_trans.h"
#include "abor1.intfb.h"

TYPE(SPEC_VIEW), ALLOCATABLE :: YLSPVVOR(:), YLSPVDIV(:)
TYPE(SPEC_VIEW), ALLOCATABLE :: YLSPVSCALAR(:)

TYPE(GRID_VIEW), ALLOCATABLE :: YLGVU(:),YLGVV(:)
TYPE(GRID_VIEW), ALLOCATABLE :: YLGVVOR(:),YLGVDIV(:)
TYPE(GRID_VIEW), ALLOCATABLE :: YLGVSCALAR(:)

TYPE(GRID_VIEW), ALLOCATABLE :: YLGVUDM(:),YLGVVDM(:)
TYPE(GRID_VIEW), ALLOCATABLE :: YLGVSCALARDM(:), YLGVSCALARDL(:)

REAL(KIND=JPRB), POINTER :: ZPSPVOR(:,:),ZPSPDIV(:,:)             ! SPECTRAL VECTOR FIELDS (IN)
REAL(KIND=JPRB), POINTER :: ZPSPSC2(:,:)                          ! SPECTRAL SURFACE SCALAR FIELDS(IN)
REAL(KIND=JPRB), POINTER :: ZPGPUV(:,:,:,:)                       ! GRID VECTOR FIELDS (OUT)
REAL(KIND=JPRB), POINTER :: ZPGP2(:,:,:)                          ! GRID SURFACE SCALAR FIELDS (OUT)

INTEGER(KIND=JPIM)          :: ISPUV                                  ! NUMBER OF INPUT SPECTRAL VECTOR FIELDS
INTEGER(KIND=JPIM)          :: IFLDXG
INTEGER(KIND=JPIM)          :: IFLDXL
INTEGER(KIND=JPIM)          :: IFLDXGUV
INTEGER(KIND=JPIM)          :: IFLDXLUV
INTEGER(KIND=JPIM)          :: IUVG                                   ! NUMBER OF OUTPUT VECTOR FIELDS
INTEGER(KIND=JPIM)          :: ISCDIM                                 ! SIZE OF OUTPUT SCALAR FIELDS ARRAY
INTEGER(KIND=JPIM)          :: IUVDIM                                 ! SIZE OF OUTPUT VECTOR FIELDS ARRAY
INTEGER(KIND=JPIM)          :: ID,IOFFSET,JLEV
INTEGER(KIND=JPIM)          :: IEND


INTEGER(KIND=JPIM),ALLOCATABLE :: IVSETUV(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IVSETSC2(:)

INTEGER(KIND=JPIM)          :: JFLD                                   ! FIELD COUNTER
LOGICAL                     :: LLSCDERS                               ! INDICATING IF DERIVATIVES OF SCALAR VARIABLES ARE REQ.
LOGICAL                     :: LLVORGP                                ! INDICATING IF GRID-POINT VORTICITY IS REQ.
LOGICAL                     :: LLDIVGP                                ! INDICATING IF GRID-POINT DIVERGENCE IS REQ.
LOGICAL                     :: LLUVDER                                ! INDICATING IF E-W DERIVATIVES OF U AND V ARE REQ.
LOGICAL                     :: LLVERBOSE                              ! INDICATING IF VERBOSE OUTPUT IS REQ.

LLVERBOSE = .FALSE.

IF (PRESENT(LDVERBOSE))  LLVERBOSE = LDVERBOSE

! 1. VECTOR FIELDS TRANSFORMATION

! CHECK IF ALL PROVIDED VECTOR FIELD INFORMATION IS CONSISTENT

IF (PRESENT(YDFU) .NEQV. PRESENT(YDFV)) CALL ABOR1("[ECTRANS_API] IYDU/YDFV")
IF (PRESENT(YDFU) .NEQV. PRESENT(YDFSPVOR)) CALL ABOR1("[ECTRANS_API] IYDU/YDFSPVOR")
IF (PRESENT(YDFU) .NEQV. PRESENT(YDFSPDIV)) CALL ABOR1("[ECTRANS_API] IYDU/YDFSPDIV")

IUVDIM = 0

! DO WE HAVE VECTOR FIELDS?

IF (PRESENT(YDFU)) THEN

  IF ((SIZE(YDFU)/= SIZE(YDFV)).OR.(SIZE(YDFU)/= SIZE(YDFSPDIV)).OR.(SIZE(YDFU)/= SIZE(YDFSPVOR))) THEN
    CALL ABOR1("[ECTRANS_API] INVALID LIST SIZES:")
  ENDIF

  YLSPVVOR = LS (YDFSPVOR, LDACC)
  YLSPVDIV = LS (YDFSPDIV, LDACC)

  YLGVU = LG (YDFU, LDACC)
  YLGVV = LG (YDFV, LDACC)

  IF ((SIZE (YLGVU) /= SIZE (YLGVV)) .OR. (SIZE (YLSPVVOR) /= SIZE (YLSPVDIV))) THEN
    CALL ABOR1("[ECTRANS_API] INCONSISTENT NUMBER OF FIELD_VIEW FOR VECTORS:")
  ENDIF
  IF (((SIZE (YLGVU) / SIZE (YDFU)) /= KFLEVG) .OR. ((SIZE (YLSPVVOR) / SIZE (YDFSPVOR)) /= KFLEVL)) THEN
    CALL ABOR1("[ECTRANS_API] INCONSISTENT KFLEVG OR KFLEVL")
  ENDIF

  IUVG = SIZE(YDFU)           ! NUMBER OF OUTPUT  VECTOR FIELDS
  ISPUV = SIZE(YDFSPVOR)

  LLUVDER  = .FALSE.
  LLVORGP = .FALSE.
  LLDIVGP = .FALSE.
  LLSCDERS = .FALSE.

  IUVDIM = 2

  IF (PRESENT(YDFUDM) .AND. PRESENT(YDFVDM))    THEN
    LLUVDER = .TRUE.
    IUVDIM = 5
    YLGVUDM = LG (YDFUDM, LDACC)
    YLGVVDM = LG (YDFVDM, LDACC)
  ENDIF
  IF (PRESENT(YDFDIV)) THEN
    LLDIVGP = .TRUE.
    IUVDIM = 5
    YLGVDIV = LG (YDFDIV, LDACC)
  ENDIF

  IF (PRESENT(YDFVOR)) THEN
    LLVORGP = .TRUE.
    IUVDIM = 6
    YLGVVOR = LG (YDFVOR, LDACC)
  ENDIF
   
  ! ALLOCATE VECTOR FIELD INPUT IN SPECTRAL SPACE
  ALLOCATE(ZPSPVOR(SIZE(YLSPVVOR),KSPEC))
  ALLOCATE(ZPSPDIV(SIZE(YLSPVDIV),KSPEC))

  ! ALLOCATE VECTOR FIELD OUTPUT IN GRID SPACE
  ALLOCATE(ZPGPUV(KPROMA,KFLEVG, IUVG * IUVDIM,KGPBLKS))
  ALLOCATE(IVSETUV(KFLEVG))

  ! COPY FROM FIELDS TO TEMPORARY ARRAYS (1D COPY THANKS TO FIELD VIEW)

  DO JFLD=1,SIZE(YLSPVVOR)
    ZPSPVOR(JFLD,:) = YLSPVVOR(JFLD)%VIEW%P(:)
    ZPSPDIV(JFLD,:) = YLSPVDIV(JFLD)%VIEW%P(:)
  ENDDO


ELSE
  ! YDFU IS NOT PROVIDED, WE DO NOT HAVE TO COMPUTE THE CORRESPONDING VECTOR OUTPUT
  ISPUV = 0
  ZPGPUV=>NULL()  
  ZPSPVOR=>NULL()
  ZPSPDIV=>NULL()
ENDIF

! 2. SCALAR FIELDS TRANSFORMATION

! CHECK IF ALL PROVIDED SCALAR FIELD INFORMATION IS CONSISTENT

IF (PRESENT(YDFSPSCALAR) .NEQV. PRESENT(YDFSCALAR)) THEN
   CALL ABOR1("[ECTRANS_API] GRID/SPEC")
ENDIF

IF (PRESENT(YDFSPSCALAR)) THEN

  IF ((SIZE(YDFSPSCALAR)/= SIZE(YDFSCALAR)))  THEN
    CALL ABOR1("[ECTRANS_API] INCONSISTENT NUMBER OF FIELD_VIEW FOR YDFSCALAR")
  ENDIF

  YLGVSCALAR = LG (YDFSCALAR, LDACC)
  YLSPVSCALAR = LS (YDFSPSCALAR, LDACC)

  IFLDXG = SIZE(YLGVSCALAR) ! NUMBER OF OUTPUT SCALAR FIELDS IN GRID SPACE

  IFLDXL = 0  ! NUMBER OF INPUT SCALAR FIELDS IN SPECTRAL SPACE
  DO JFLD = 1, SIZE(YLGVSCALAR) ! NUMBER OF OUTPUT SCALAR FIELDS IN GRID SPACE
    IF (ASSOCIATED(YLSPVSCALAR(JFLD)%VIEW%P)) THEN
      IFLDXL = IFLDXL + 1
    ENDIF
  END DO 

  ISCDIM = 1
  IF (PRESENT(YDFSCALARDM) .AND. PRESENT(YDFSCALARDL)) THEN
    LLSCDERS = .TRUE.
    ISCDIM = ISCDIM + 2
    YLGVSCALARDM = LG (YDFSCALARDM, LDACC)
    YLGVSCALARDL = LG (YDFSCALARDL, LDACC)
  ENDIF


   ! ALLOCATE SCALAR FIELD INPUT IN SPECTRAL SPACE
  ALLOCATE(ZPSPSC2(IFLDXL,KSPEC))

  ! ALLOCATE SCALAR FIELD OUTPUT IN GRID SPACE
  ALLOCATE(ZPGP2(KPROMA,IFLDXG * ISCDIM,KGPBLKS))
  ALLOCATE(IVSETSC2(IFLDXG))

 ! COPY SCALAR SPECTRAL FIELDS TO TEMPORARY ARRAYS (1D COPY THANKS TO FIELD VIEW)
  ID = 1
  DO JFLD = 1, SIZE(YLSPVSCALAR) ! NUMBER OF OUTPUT SCALAR FIELDS IN GRID SPACE
   IF (ASSOCIATED(YLSPVSCALAR(JFLD)%VIEW%P)) THEN
     ZPSPSC2(ID,:) = YLSPVSCALAR(JFLD)%VIEW%P(:)
     ID = ID + 1 
   ENDIF
  ENDDO

   DO JFLD=1, IFLDXG
    IVSETSC2(JFLD) = YLGVSCALAR(JFLD)%IVSET
   ENDDO


  DO JFLD=1,IUVG
    DO JLEV=1,KFLEVG
     ID = JLEV + (JFLD -1) * KFLEVG
     IF (JFLD .EQ. 1) IVSETUV(JLEV) = YLGVU(ID)%IVSET
     IF (IVSETUV(JLEV) .NE. YLGVU(ID)%IVSET) CALL ABOR1("[ECTRANS_API] IVSETUV INCONSISTENT WITH YLGVU%IVSET")
     IF (IVSETUV(JLEV) .NE. YLGVV(ID)%IVSET) CALL ABOR1("[ECTRANS_API] IVSETUV INCONSISTENT WITH YLGVV%IVSET")
    ENDDO
  ENDDO

ELSE
  IFLDXG = 0
  ZPGP2=>NULL()
  ZPSPSC2=>NULL()  
ENDIF

! 3. CALL INV_TRANS

IF (PRESENT (FSPGL_PROC) .AND. .FALSE.) THEN
  CALL INV_TRANS (PSPVOR=ZPSPVOR,PSPDIV=ZPSPDIV,PGPUV=ZPGPUV,KVSETUV=IVSETUV, &
                & PSPSC2=ZPSPSC2,PGP2=ZPGP2,KVSETSC2=IVSETSC2, &
                & LDSCDERS=LLSCDERS, LDVORGP=LLVORGP, LDDIVGP=LLDIVGP, LDUVDER=LLUVDER,  &
                & KPROMA=KPROMA,FSPGL_PROC=FSPGL_PROC)
ELSE
  CALL INV_TRANS(PSPVOR=ZPSPVOR,PSPDIV=ZPSPDIV,PGPUV=ZPGPUV,KVSETUV=IVSETUV, &
               & PSPSC2=ZPSPSC2,PGP2=ZPGP2, KVSETSC2=IVSETSC2, &
               & LDSCDERS=LLSCDERS, LDVORGP=LLVORGP, LDDIVGP=LLDIVGP, LDUVDER=LLUVDER,  &
               & KPROMA=KPROMA)
ENDIF

! 4. COPY BACK DATA TO FIELDS

! REMOVE GARBAGE AT THE END OF ARRAYS

IEND = KGPTOT - KPROMA * (KGPBLKS - 1)
ZPGPUV (IEND+1:, :, :, KGPBLKS) = 0
ZPGP2 (IEND+1:, :, KGPBLKS) = 0

! COPY VECTOR FIELDS BACK FROM TEMPORARY VECTOR ARRAYS

IOFFSET = 0

IF (LLVORGP) THEN
  DO JFLD=1,IUVG
    DO JLEV=1,KFLEVG
     ID = JLEV + (JFLD -1) * KFLEVG
     YLGVVOR(ID)%VIEW%P(:,:) = ZPGPUV(:, JLEV,JFLD+IOFFSET*IUVG,:)
    ENDDO
  ENDDO
  IOFFSET = IOFFSET + 1
ENDIF

IF (LLDIVGP) THEN
  DO JFLD=1,IUVG
    DO JLEV=1,KFLEVG
     ID = JLEV + (JFLD -1) * KFLEVG
     YLGVDIV(ID)%VIEW%P(:,:) = ZPGPUV(:, JLEV,JFLD+IOFFSET*IUVG,:)
    ENDDO
  ENDDO
  IOFFSET = IOFFSET + 1
ENDIF

DO JFLD=1,IUVG
  DO JLEV=1,KFLEVG
     ID = JLEV + (JFLD -1) * KFLEVG
     YLGVU(ID)%VIEW%P(:,:) =  ZPGPUV(:,JLEV,JFLD+IOFFSET*IUVG,:)
     YLGVV(ID)%VIEW%P(:,:) =  ZPGPUV(:,JLEV,JFLD+(IOFFSET+1)*IUVG,:)
  ENDDO
ENDDO

IOFFSET = IOFFSET + 2
IF (LLUVDER) THEN
  DO JFLD=1,IUVG
    DO JLEV=1,KFLEVG
     ID = JLEV + (JFLD -1) * KFLEVG
     YLGVUDM(ID)%VIEW%P(:,:) = ZPGPUV(:,JLEV,JFLD+IUVG*IOFFSET,:)
     YLGVVDM(ID)%VIEW%P(:,:) = ZPGPUV(:,JLEV,JFLD+IUVG*(IOFFSET+1),:)
   ENDDO
 ENDDO
ENDIF

! COPY SCALAR FIELDS BACK FROM TEMPORARY SCALAR ARRAYS

DO JFLD=1, IFLDXG
  YLGVSCALAR(JFLD)%VIEW%P(:,:) = ZPGP2(:,JFLD,:)
ENDDO

IF (LLSCDERS) THEN
  DO JFLD=1,IFLDXG
   YLGVSCALARDM(JFLD)%VIEW%P(:,:) = ZPGP2(:, JFLD+IFLDXG,:)
   YLGVSCALARDL(JFLD)%VIEW%P(:,:) = ZPGP2(:, JFLD+(2*IFLDXG),:)
  ENDDO
ENDIF

DEALLOCATE(ZPSPVOR)
DEALLOCATE(ZPSPDIV)
DEALLOCATE(ZPSPSC2)
DEALLOCATE(ZPGPUV)
DEALLOCATE(ZPGP2)
DEALLOCATE(IVSETUV)
DEALLOCATE(IVSETSC2)

END SUBROUTINE INV_TRANS_FIELD_API
